Mavenizing async-profiler Java library
jvm-profiling-tools/async-profiler pull request #365
Opened 2020-11-03 00:25 UTC by JigarJoshi

#93 

Step 1: Mavenize the Java library <-- this PR takes care for this
Step 2: Create friendly Java API (take care of extracting and loading library .so)
Step 3: publish it to maven central

2020-11-27 09:58 UTC, incubos commented
Could you please temporarily publish the artifact from [your fork using JitPack](https://jitpack.io/#JigarJoshi/async-profiler) and test it (i.e. the library is loaded successfully)?

2020-11-27 10:11 UTC, incubos requested changes
Multiplatform support is needed if we are going to publish a single artifact.

2020-11-27 10:11 UTC, incubos commented on pom.xml
> +                                <argument>build/libasyncProfiler.so</argument>
`async-profiler` supports [many platforms](https://github.com/jvm-profiling-tools/async-profiler#download) having prebuilt libraries and Maven artifact we are going to publish is expected to be used from any supported platform, so we have to find a way to pack all the binaries.

2020-11-28 18:47 UTC, apangin commented
Hi,
Sorry for the delay - that was a rather busy month for me.

First, please create PRs against v2.0 branch - it will become mainline soon. No new features are planned for 1.8 - it will remain only for bugfixes.

My main concern is how to package async-profiler agent binaries. As Vadim noticed, async-profiler supports many platforms, each requiring a separate binary. In future, the number of platforms will likely increase (think of Apple M1, for example). I don't like an idea of packaging all possible binaries into a single JAR, otherwise it'll get enormously large. Furthermore, I expect that some users will prefer to install async-profiler package with the OS-specific package manager like RPM, and some will build the profiler on their own. Therefore, I think it makes sense to create a separate Maven artifact with the API only, and separate artifacts with `.so` for each individual platform.

Side note: by default, `make` builds the profiler agent, `jattach` helper, API jar, and converters jar. When preparing `libasyncProfiler.so`, we may build just the agent library and skip other steps.

2021-01-14 02:21 UTC, apangin commented
Closing PR, since it has been superseded by the ongoing work within #93.

2021-01-14 02:21 UTC, closed without merging